spring.datasource.driver-class-name= org.postgresql.Driver
spring.datasource.url= jdbc:postgresql://localhost:5432/myblogbackapp
spring.datasource.username= postgres
spring.datasource.password= postgres

app.upload-dir = /Users/bibik/Downloads/uploads
app.upload-dir.allowed-image-extensions = .jpg, .jpeg, .png, .webp